name: Flutter CI

on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"

jobs:
  build:
    strategy:
      matrix:
        platform: [self-hosted]
        java-version: [17]
        android-compile-sdk: [30]
        android-build-tools: [30.0.3]
        android-sdk-tools: [9477386]
        flutter-version: ["3.10.6"]
        channel: ["stable"]
        arch: [x64]
    runs-on: ${{ matrix.platform }}
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk-root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java-version }}

      - name: Linux - Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y sqlite3 libsqlite3-dev

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: ${{ matrix.channel }}
          architecture: ${{ matrix.arch }}

      # Mark the flutter directory as safe.
      - run: git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ matrix.channel }}-${{ matrix.flutter-version }}-${{ matrix.arch }}

      # Print installed flutter version.
      - run: flutter --version

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: dart format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Run widget tests for our flutter project.
      - run: flutter test

      # Run integration tests for our flutter project.
      - name: Run integration tests
        timeout-minutes: 30
        run: |
          apt-get update && apt-get install -y unzip wget cpu-checker
          kvm-ok
          install -d $ANDROID_SDK_ROOT
          wget --no-verbose --output-document=$ANDROID_SDK_ROOT/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${{matrix.android-sdk-tools}}_latest.zip
          unzip -q -d "$ANDROID_SDK_ROOT/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools.zip"
          mv -T "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/tools"
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator

          sdkmanager --version

          yes | sdkmanager --licenses
          sdkmanager "platforms;android-${{matrix.android-compile-sdk}}"
          sdkmanager "platform-tools"
          sdkmanager "build-tools;${{matrix.android-build-tools}}"
          sdkmanager --list
          sdkmanager "system-images;android-${{matrix.android-compile-sdk}};google_apis;arm64-v8a"
          sdkmanager "emulator"
          echo "no" | avdmanager create avd --force -n test_emulator -k "system-images;android-${{matrix.android-compile-sdk}};google_apis;arm64-v8a"
          emulator -list-avds
          adb start-server
          echo "Starting emulator..."
          emulator -avd test_emulator -skin 600x1024 -no-audio -no-window -no-boot-anim -accel on -gpu swiftshader_indirect -debug -all & adb wait-for-device
          echo "Emulator started successfully."
          flutter devices
          flutter test integration_test -d emulator-5554

      # Build apk.
      - run: flutter build apk

      # Upload generated apk to the artifacts.
      - name: Upload apk to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
