name: Flutter CI

on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"

jobs:
  build:
    strategy:
      matrix:
        platform: [self-hosted]
        java-version: [17]
        android-compile-sdk: [27]
        android-build-tools: [33.0.2]
        android-sdk-tools: [9477386]
        flutter-version: ["3.10.6"]
        channel: ["stable"]
        arch: [x64]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java-version }}

      - name: Setup android SDK
        run: |
          apt-get update && apt-get install -y unzip wget

          export ANDROID_HOME="${PWD}/android-sdk-root"
          install -d $ANDROID_HOME
          wget --no-verbose --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${{matrix.android-sdk-tools}}_latest.zip
          unzip -q -d "$ANDROID_HOME/cmdline-tools" "$ANDROID_HOME/cmdline-tools.zip"
          mv -T "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/tools"
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/cmdline-tools/tools/bin

          sdkmanager --version

          yes | sdkmanager --licenses > /dev/null || true
          sdkmanager "platforms;android-${{matrix.android-compile-sdk}}"
          sdkmanager "platform-tools"
          sdkmanager "build-tools;${{matrix.android-build-tools}}"
          sdkmanager --list
          sdkmanager "system-images;android-${{matrix.android-compile-sdk}};google_apis;arm64-v8a"
          sdkmanager "emulator"
          echo "no" | avdmanager create avd --force -n test_emulator -k "system-images;android-${{matrix.android-compile-sdk}};google_apis;arm64-v8a"
          $ANDROID_HOME/emulator/emulator -list-avds
          $ANDROID_HOME/emulator/emulator -avd test_emulator -no-audio -no-window -no-boot-anim -no-accel &

      - name: Linux - Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y sqlite3 libsqlite3-dev cmake ninja-build

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: ${{ matrix.channel }}
          architecture: ${{ matrix.arch }}

      # Mark the flutter directory as safe.
      - run: git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ matrix.channel }}-${{ matrix.flutter-version }}-${{ matrix.arch }}

      # Print installed flutter version.
      - run: flutter --version

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: dart format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Run widget tests for our flutter project.
      - run: flutter test

      # List all the available devices.
      - run: flutter devices

      # Run integration tests for our flutter project.
      - run: flutter test integration_test/

      # Upload generated apk to the artifacts.
      - name: Upload apk to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
